# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EmptyDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
	pod 'MJRefresh'
	pod 'DZNEmptyDataSet'
  # Pods for EmptyDemo

  target 'EmptyDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'EmptyDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
